analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 1067766,\\n  \\"name\\"\: \\"Nutrilon\\",\\n  \\"teamId\\"\: 1053708,\\n  \\"organizationId\\"\: 1108700,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 1053708\\n}"
analytics.testresult.autosubmit=true
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=true
analytics.onpremise.enable=false
