<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Verifikasi OTP</name>
   <tag></tag>
   <elementGuidId>db8b9bdd-917e-46ae-8d81-0f086ae76e21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-block.mb-5.btn-verifikasi.w-75.m-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d17c0099-023b-426f-b251-57fca60d3bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8065147-f36c-4bac-b347-5eb855812842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block mb-5 btn-verifikasi w-75 m-auto</value>
      <webElementGuid>e82a28bd-1ff3-463e-ba39-4888670dc196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>step-3</value>
      <webElementGuid>64a12a07-a646-4762-a3d3-86799a2e40b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Verifikasi
                                    </value>
      <webElementGuid>5c454f58-41af-4be2-9cbe-f14aa2a36869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;content justify-content-center&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-12 col-md-8&quot;]/div[@class=&quot;registration__form&quot;]/div[@class=&quot;registration__content registration__otp mb-4&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;content__card rounded&quot;]/form[1]/button[@class=&quot;btn btn-primary btn-block mb-5 btn-verifikasi w-75 m-auto&quot;]</value>
      <webElementGuid>55860dc8-3128-41b3-91ca-d134f43cf26b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>5bf7d944-05dc-4ffd-8fdf-72c2471335fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Ulang'])[1]/following::button[1]</value>
      <webElementGuid>56bcd936-0269-4d78-bc83-94f1e3718cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya Hapus'])[1]/following::button[2]</value>
      <webElementGuid>46ea0a44-8d7c-4805-adb7-7a678bd1bd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pernyataan Privasi akan Data Anda | Nutriclub'])[1]/preceding::button[1]</value>
      <webElementGuid>4627bb9b-1ff2-4155-b0e7-f2af5565cec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya Setuju'])[1]/preceding::button[1]</value>
      <webElementGuid>3f05a5ff-9f5c-413d-a880-0393ed4d5769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verifikasi']/parent::*</value>
      <webElementGuid>734c08a0-11d4-4028-99e9-fa44c3a90a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>c2b868e9-3c9a-4c71-82b8-a4679976109c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                        Verifikasi
                                    ' or . = '
                                        Verifikasi
                                    ')]</value>
      <webElementGuid>608a8831-d8e4-4c6f-82e9-5b3767f7d4db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
