<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text Silahkan masukkan kode OTP</name>
   <tag></tag>
   <elementGuidId>ad6979bb-c8f3-49d6-9430-a4e747ee9507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya Hapus'])[1]/following::p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.content__card-description.container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1d442efa-aa33-4292-a067-6619410350db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content__card-description container</value>
      <webElementGuid>0cf6547c-2e75-4ee8-a41e-2a6490181b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-recent-on-screen2446017_1747</name>
      <type>Main</type>
      <value>288</value>
      <webElementGuid>ff48a2be-8326-48cc-857c-634fbe74398c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-first-on-screen2446017_1747</name>
      <type>Main</type>
      <value>288</value>
      <webElementGuid>3b2d0ac5-bee1-4a82-8da7-03b9ab50e44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-total-visible-time2446017_1747</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>de1080d4-5b9c-421e-8b6c-5a31ca1b4dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-has-fired2446017_1747</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>de4449c7-595d-4d30-9d39-dc73482cc6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-recent-on-screen2446017_1974</name>
      <type>Main</type>
      <value>299</value>
      <webElementGuid>26fc9fa4-b600-4d8c-bc39-15ed4f0d9abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-first-on-screen2446017_1974</name>
      <type>Main</type>
      <value>299</value>
      <webElementGuid>f7cc4f10-7f03-4022-aa8f-ae43e6b8c48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-total-visible-time2446017_1974</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>89b008f5-04da-4e5e-96ab-00b312dbc712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-has-fired2446017_1974</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2ceb83c0-5f80-4d0c-84ee-30db345b84cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Silahkan masukkan kode OTP.</value>
      <webElementGuid>dcad58eb-e60c-400c-858b-3eb217484698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;content justify-content-center&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-12 col-md-8&quot;]/div[@class=&quot;registration__form&quot;]/div[@class=&quot;registration__content registration__otp mb-4&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;content__card rounded&quot;]/p[@class=&quot;content__card-description container&quot;]</value>
      <webElementGuid>7d665d04-c2ab-40ff-915c-c29d4897cbe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya Hapus'])[1]/following::p[1]</value>
      <webElementGuid>30d7b4ee-7f61-4724-9500-593c5f0bfe09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/following::p[1]</value>
      <webElementGuid>3126d6e2-27ac-4584-9613-dc9f15d9728e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Ulang'])[1]/preceding::p[1]</value>
      <webElementGuid>a0f836aa-10d7-4b9f-bdd7-9714628eaea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi'])[1]/preceding::p[3]</value>
      <webElementGuid>a5e9f255-f2fe-4130-88b4-7dde45d99907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Silahkan masukkan kode OTP.']/parent::*</value>
      <webElementGuid>bd09938e-9e98-4032-a7d0-e9ee86efa18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/p</value>
      <webElementGuid>b15852de-64d4-4abf-88c1-a306b7a872a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' Silahkan masukkan kode OTP.' or . = ' Silahkan masukkan kode OTP.')]</value>
      <webElementGuid>4032cb06-15e5-4770-abb3-8ba33a52dfab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
