<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo-nutriclub</name>
   <tag></tag>
   <elementGuidId>8906e0b2-9157-405a-b1fc-724c017e9d52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo-nutriclub</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarNav']/div/ul/div[2]/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>787ba6fc-f8ef-45a3-9a7a-53fccc657cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>eb690cd3-5af1-446d-beef-5ed0f45e70a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>41</value>
      <webElementGuid>6e420c04-1e10-4c86-b796-5cd6cbc22269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-nutriclub</value>
      <webElementGuid>75e3023d-9b65-4f61-a96b-77aa2d050987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f5d9e129-52ea-47e9-bc92-bc96b2415743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo-nutriclub | © logo nutriclub</value>
      <webElementGuid>85901d6c-2046-4f65-958b-a058be8d8864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>logo nutriclub | © logo nutriclub</value>
      <webElementGuid>42487e8c-3bfa-4660-9996-1616d8c03c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/logo/image-thumb__2485__website-logo/logo-nutriclub.webp</value>
      <webElementGuid>824055c0-da60-4f1b-8aaa-ed86f7d37235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/logo/image-thumb__2485__website-logo/logo-nutriclub.webp 1x, https://d6h6jrckowxli.cloudfront.net/logo/image-thumb__2485__website-logo/logo-nutriclub@2x.webp 2x</value>
      <webElementGuid>bcf0ca99-2430-4e71-bee2-40f98cb37846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarNav&quot;)/div[@class=&quot;col col-lg-9 p-0&quot;]/ul[@class=&quot;navbar-nav header__tool text-center&quot;]/div[@class=&quot;navbar-nav__logo&quot;]/li[@class=&quot;nav-item header__logo&quot;]/a[@class=&quot;nav-link mt-0 mb-0&quot;]/img[@class=&quot;logo-nutriclub&quot;]</value>
      <webElementGuid>0424e0a1-bd0b-418b-89b4-e5661b817ea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarNav']/div/ul/div[2]/li/a/img</value>
      <webElementGuid>45fd34b1-d2c4-4c04-b2e8-cbad1a505437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo-nutriclub | © logo nutriclub']</value>
      <webElementGuid>b7f138ea-ca14-4591-95ad-294ee848020f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>44d0ffdc-ca62-49f1-8dee-1c8f48d168bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'logo-nutriclub | © logo nutriclub' and @title = 'logo nutriclub | © logo nutriclub' and @src = 'https://d6h6jrckowxli.cloudfront.net/logo/image-thumb__2485__website-logo/logo-nutriclub.webp']</value>
      <webElementGuid>0af24d8f-2ef5-4aa9-b047-0236703e4810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
