<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aktifkan Semua Cookie</name>
   <tag></tag>
   <elementGuidId>59d4329d-d142-4419-bc61-8a35d81f6f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#footer_tc_privacy_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='footer_tc_privacy_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04e9c3f2-b687-4cbe-bdad-e67aa4ac85d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>footer_tc_privacy_button</value>
      <webElementGuid>69927fd0-df3b-479e-849c-83eb2e4db988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tc-reset-css tc-privacy-button</value>
      <webElementGuid>045f6141-4003-4444-9039-ac8689e6affe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91f421d6-552d-4e0c-85c2-9a5e733d0f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aktifkan Semua Cookie</value>
      <webElementGuid>aaa658bf-6303-4c44-9198-1c84e231ff74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktifkan Semua Cookie</value>
      <webElementGuid>9b685689-168e-4f59-b6c9-11e903b03001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer_tc_privacy_button&quot;)</value>
      <webElementGuid>d34bd30f-7b49-4e6f-8720-8d69fe732aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='footer_tc_privacy_button']</value>
      <webElementGuid>46548fa2-56f1-4cf3-bc96-fcf442e6802e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer_tc_privacy_container_button']/button[2]</value>
      <webElementGuid>6ad65a14-7de2-4b70-a98c-013b88736c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan Cookie'])[1]/following::button[1]</value>
      <webElementGuid>85edaa4a-7bdc-4c28-9f66-21eaa2795933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kontak kami'])[2]/following::button[2]</value>
      <webElementGuid>7255eefb-4b71-4363-94fe-08bf90fa72e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aktifkan Semua Cookie']/parent::*</value>
      <webElementGuid>98436667-0269-4098-8443-7bd9dd31d67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/button[2]</value>
      <webElementGuid>2c559381-0b71-4a9c-9c8e-dcdded31458e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'footer_tc_privacy_button' and @type = 'button' and @title = 'Aktifkan Semua Cookie' and (text() = 'Aktifkan Semua Cookie' or . = 'Aktifkan Semua Cookie')]</value>
      <webElementGuid>865ba8ef-d78f-41f8-a11d-44c3bd7801b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
