<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label Field No Handphone</name>
   <tag></tag>
   <elementGuidId>dceb33a5-3246-4c0e-826a-f188de276354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.required</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>76ec8f85-a6ae-417a-a81e-c4f3da73e758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>0</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>60e23dab-18f0-4855-b128-c6f53ebfb917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No Handphone</value>
      <webElementGuid>0de5a487-cab1-4832-b8dd-9f3302eef63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6f4a9b8f-b43d-489c-bd55-b9a45a1daac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>bdc8d94b-1c0c-483a-8d92-7bc002794da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>089a5102-9120-48ba-9df8-919a9296473c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No Handphone</value>
      <webElementGuid>15e67edb-023f-4df6-a8d7-065f20545ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-4&quot;)/div[@class=&quot;row login__wrapper&quot;]/div[@class=&quot;col-10 offset-1 col-lg-10 offset-lg-2&quot;]/div[@class=&quot;content__card rounded&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 offset-md-2&quot;]/div[@class=&quot;text-left&quot;]/label[@class=&quot;required&quot;]</value>
      <webElementGuid>356e014b-0ac4-4cbf-ade3-29be538f2412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@value='']</value>
      <webElementGuid>8ece5c94-7f32-4e19-b23f-85254e51ef2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-4']/div/div/div[2]/div/div/div/label</value>
      <webElementGuid>4d3780c6-3a93-4c84-bd02-1675f729c4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Nutriclub, dapatkan info seputar tumbuh kembang anak'])[1]/following::label[1]</value>
      <webElementGuid>738fc25a-d77b-46d8-a860-d80ec4263788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya Hapus'])[1]/following::label[1]</value>
      <webElementGuid>4fe4ddc1-5c7f-424b-b7cc-951bd0d7b4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/preceding::label[1]</value>
      <webElementGuid>530794b6-f28c-418b-adaf-7bf7618c5be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi'])[1]/preceding::label[2]</value>
      <webElementGuid>86a03999-efa5-496e-bc24-ea17930b8873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No Handphone']/parent::*</value>
      <webElementGuid>e6bafe2d-8bca-4c3a-adf4-d60ba46df1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>9ad38710-2525-4c25-b734-c2ea8c0334d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@placeholder = 'Masukkan No Handphone' and (text() = 'No Handphone' or . = 'No Handphone')]</value>
      <webElementGuid>784bbda1-8706-4b6b-96f0-772ad95c4ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
