<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text Pelajari lebih lanjut Captcha</name>
   <tag></tag>
   <elementGuidId>f7c2dcfc-6510-4715-b9fe-e07ed48c9973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.label-recaptcha > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-4']/div/div/div[2]/div[5]/div/p[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35b279f0-0d09-42a4-9463-dbb99412b3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://google.com/recaptcha</value>
      <webElementGuid>6d9c9ff9-2909-4e44-b2f0-adfa58000130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9f4eccf5-1f80-4422-a517-6248aeaf5dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pelajari lebih lanjut.</value>
      <webElementGuid>23aa771f-a889-493e-a3a1-f231493eb4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-4&quot;)/div[@class=&quot;row login__wrapper&quot;]/div[@class=&quot;col-10 offset-1 col-lg-10 offset-lg-2&quot;]/div[@class=&quot;content__card rounded&quot;]/div[@class=&quot;row d-flex justify-content-center&quot;]/div[@class=&quot;col-11 col-md-8 label-recaptcha-wrapper&quot;]/p[@class=&quot;label-recaptcha&quot;]/a[1]</value>
      <webElementGuid>635ac6e2-6e3e-4d40-8197-93872fc39058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-4']/div/div/div[2]/div[5]/div/p[2]/a</value>
      <webElementGuid>cab1a3de-909e-48f7-bb4a-7d34b1c2ed0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pelajari lebih lanjut.')]</value>
      <webElementGuid>2916cf80-236a-4f51-925e-3756467e2a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar di sini'])[1]/following::a[1]</value>
      <webElementGuid>aacd878a-49c9-4d24-85e5-fce6e68b738a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mama,'])[1]/preceding::a[1]</value>
      <webElementGuid>1cbabf04-16da-4ec3-9e2a-2e47a435c0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok, saya mengerti!'])[1]/preceding::a[1]</value>
      <webElementGuid>21be6ca6-4798-48f1-a1fd-a6890f147eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pelajari lebih lanjut.']/parent::*</value>
      <webElementGuid>c55a6261-64aa-4736-80e2-29be4089d432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://google.com/recaptcha')]</value>
      <webElementGuid>16673211-10fb-4645-8673-8c7a55d09c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>3aee8389-e265-48d9-818c-c14ef2f691f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://google.com/recaptcha' and (text() = 'Pelajari lebih lanjut.' or . = 'Pelajari lebih lanjut.')]</value>
      <webElementGuid>a80748e2-af73-4ed2-9c01-e8265e1a73b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
