<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aktifkan Semua Cookie</name>
   <tag></tag>
   <elementGuidId>87fd329d-5327-4fe8-b5ce-e8f17c3130d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#footer_tc_privacy_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='footer_tc_privacy_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8cb6dd79-2532-4e95-a3aa-22ce1fa4c583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>footer_tc_privacy_button</value>
      <webElementGuid>8b5010d1-cece-49d6-8025-7618939ce42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tc-reset-css tc-privacy-button</value>
      <webElementGuid>04e8e26f-5e97-4e03-a898-e864788a544d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79d97d23-ca52-4438-b0de-8a83d7e2e2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aktifkan Semua Cookie</value>
      <webElementGuid>708ba3e8-fa69-4992-984e-9e96d012b0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktifkan Semua Cookie</value>
      <webElementGuid>55cb446c-3858-45fe-9571-6a482a350538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer_tc_privacy_button&quot;)</value>
      <webElementGuid>35f1087f-f048-45a1-9b7d-ac8cb179a99e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='footer_tc_privacy_button']</value>
      <webElementGuid>f8b9008a-2c43-47ca-92f4-a8e0a8670925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer_tc_privacy_container_button']/button[2]</value>
      <webElementGuid>aeb712d0-cbab-4459-b636-b6f7a8319f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan Cookie'])[1]/following::button[1]</value>
      <webElementGuid>595cd2ec-21d2-44d4-a55f-45d29eeec4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kontak kami'])[2]/following::button[2]</value>
      <webElementGuid>d18f09e6-c527-47c0-9bca-9d8b8ee3621a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aktifkan Semua Cookie']/parent::*</value>
      <webElementGuid>219a88c2-aad4-4702-b50f-351bf47cebe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/button[2]</value>
      <webElementGuid>9020c930-a8ee-4642-b9ff-668026175c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'footer_tc_privacy_button' and @type = 'button' and @title = 'Aktifkan Semua Cookie' and (text() = 'Aktifkan Semua Cookie' or . = 'Aktifkan Semua Cookie')]</value>
      <webElementGuid>bacf83e9-3638-4bb2-8e65-8b34aa4a69e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
