<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sub Menu Artikel Anak - Imunitas</name>
   <tag></tag>
   <elementGuidId>df30d5ad-635a-43f6-b9ad-e27360564377</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Imunitas')])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81e27527-90d4-43b7-989c-ec93e28e0fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/artikel?kategori=anak&amp;topik=imunitas</value>
      <webElementGuid>b8276520-7480-471b-a9fe-15d781d662ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-item fading</value>
      <webElementGuid>ee8d2dab-759a-42d2-9057-c28b09def019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imunitas</value>
      <webElementGuid>30700809-d78d-48f0-9802-347c95c35040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;search__results navbar-nav mobile d-block animated fadeInRight&quot;]/div[@class=&quot;hamburger-menu&quot;]/div[@class=&quot;hamburger-menu__lists-wrapper&quot;]/ul[@class=&quot;hamburger-menu__lists-item&quot;]/li[@class=&quot;hamburger-menu__item have-sub-menu&quot;]/div[@class=&quot;hamburger-menu__item sub-item show&quot;]/div[@class=&quot;sub-item-list child list-item-level-2&quot;]/ul[@class=&quot;list-item-wrapper parent list-item-level-3&quot;]/li[@class=&quot;list-item child list-item-level-3&quot;]/a[@class=&quot;sub-item fading&quot;]</value>
      <webElementGuid>42c71294-357d-450b-afbc-6b921e1b96f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Imunitas')])[3]</value>
      <webElementGuid>c0077585-1657-4d8a-8fd1-248909da3062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak (1-5 Tahun)'])[2]/following::a[1]</value>
      <webElementGuid>30ad115a-e7af-49bc-b838-18a8c8b25b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nutrisi'])[2]/following::a[2]</value>
      <webElementGuid>379af453-d2ac-4892-bd80-605fa89346f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perkembangan Otak'])[2]/preceding::a[1]</value>
      <webElementGuid>b15cb7f0-414b-4ddf-aed1-fbd6d0cea3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kesehatan'])[3]/preceding::a[2]</value>
      <webElementGuid>ae833293-6eaf-4513-816b-0ed7885d9fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/artikel?kategori=anak&amp;topik=imunitas')]</value>
      <webElementGuid>01bfe068-ee3f-41be-b216-67f50b70e378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/a</value>
      <webElementGuid>da3aa67e-215c-4c2c-88cc-3eda5c59b732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/artikel?kategori=anak&amp;topik=imunitas' and (text() = 'Imunitas' or . = 'Imunitas')]</value>
      <webElementGuid>812ecb6f-f99d-4476-ae69-a72a5a36b272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
