<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Alert Nama anak maksimal 40 karakter</name>
   <tag></tag>
   <elementGuidId>5c16dafb-3a11-4bc1-8a3c-3dcbf20f3e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Nama anak maksimal 40 karakter' or . = 'Nama anak maksimal 40 karakter')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>67d6d66f-d2f4-4c0c-b77f-fa212067e13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>d8a75985-5894-44a6-89dd-d27794d197b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama anak maksimal 40 karakter</value>
      <webElementGuid>cfbeb8ae-4588-4ba3-a134-47fdbe827268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/span[@class=&quot;error&quot;]</value>
      <webElementGuid>50e2ac9f-6aee-4dfd-9b65-45ee1de4d475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Nama anak maksimal 40 karakter' or . = 'Nama anak maksimal 40 karakter')]</value>
      <webElementGuid>bfef046b-e556-4caa-99fb-4942e3bbf207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
