<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Alert Nama lengkap maksimal 40 karakter</name>
   <tag></tag>
   <elementGuidId>70ec221d-068f-485b-b873-a87f0afcb1b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='membership-register']/div/div/div/form/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2beb0753-94b5-4671-b9e0-b8157c75c605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>48ce86d3-d59b-425a-a1cd-3617f3eeefd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama lengkap maksimal 40 karakter</value>
      <webElementGuid>3ed78df4-3290-41d8-b450-14612abdf80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;membership-register&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/form[@class=&quot;registration_form&quot;]/div[@class=&quot;register__form&quot;]/div[@class=&quot;registration__content&quot;]/div[@class=&quot;content__input mb-2&quot;]/span[@class=&quot;error&quot;]</value>
      <webElementGuid>960a3738-ed3e-42bc-949e-9c736932f3c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='membership-register']/div/div/div/form/div/div/div/span</value>
      <webElementGuid>ea9c8969-6c2f-460d-b2bd-1765b78385f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Lengkap Mama'])[1]/following::span[1]</value>
      <webElementGuid>b534bdf7-5566-4ff1-858d-1d2e650aea92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya Hapus'])[1]/following::span[1]</value>
      <webElementGuid>bf8c6b98-6973-47f7-96cc-34fef5e7c356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Handphone Mama'])[1]/preceding::span[1]</value>
      <webElementGuid>3d27cbaf-a6d2-45a3-bade-725232af1ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor ponsel (terhubung WhatsApp) wajib diisi'])[1]/preceding::span[1]</value>
      <webElementGuid>38be1e1e-8dc0-40ed-9500-c2143ab002ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama lengkap maksimal 40 karakter']/parent::*</value>
      <webElementGuid>7e85667b-313f-43f5-90b3-4dd14cd8d38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span</value>
      <webElementGuid>4cbe9735-e7b5-4d42-a11a-c65cc7a1ae78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Nama lengkap maksimal 40 karakter' or . = 'Nama lengkap maksimal 40 karakter')]</value>
      <webElementGuid>cc088d36-3593-471d-bd47-768ecae78e0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
