<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field DOB Anak</name>
   <tag></tag>
   <elementGuidId>7737914e-2bb0-4968-ab8d-37623651a105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#children_dob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='children_dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4217a9aa-c695-4d6d-8450-3e707a407cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86694976-64c1-4558-acea-d2f641dc0d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>children_dob</value>
      <webElementGuid>8462c362-c8e5-4bb3-b348-07c26f1011cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>children_dob</value>
      <webElementGuid>687ab612-fdde-462a-8a66-95ddb8e03e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>childBirthday form-control</value>
      <webElementGuid>1c560419-316e-4e6b-af5f-bc88ce2ec1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 14-02-2020</value>
      <webElementGuid>7f9c450b-39ae-4266-b833-a7689e8481a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c51dc518-fb24-4583-84b1-1759f3420550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;children_dob&quot;)</value>
      <webElementGuid>4e950184-0e76-4ce6-8961-374b5c6796e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='children_dob']</value>
      <webElementGuid>44a6ee10-68b5-43d6-9b36-cec5dd5a6b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='membership-register']/div/div/div/form/div/div[4]/div[2]/div[2]/input[2]</value>
      <webElementGuid>abb1becd-9290-4793-9808-76e6f11909f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>202d5d5c-d7b1-4890-999b-d392e430e90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'children_dob' and @id = 'children_dob' and @placeholder = 'Contoh: 14-02-2020']</value>
      <webElementGuid>ed4c3dec-5d2a-4835-9c89-8ecc83ce0d0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
