<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Nama Lengkap Anak</name>
   <tag></tag>
   <elementGuidId>79eb8ebb-816a-4419-b047-75fc742eded0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#children_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='children_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>244445c7-abc1-4bc2-b51a-d285c8cc3316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a641276-965a-4bb0-a6c3-25fab7c6eb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>children_name</value>
      <webElementGuid>1f562e9c-8956-4aa9-a4ed-03fc11851f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>children_name</value>
      <webElementGuid>44c0e154-01d8-48fb-a28e-6f6499863a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>258b439e-3a6a-45dc-87c5-8fefb6746e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Lengkap Anak</value>
      <webElementGuid>9dc4e26e-03e6-427f-806e-64d224be90dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>94c40e5e-9fea-413b-abc4-55393ba3e147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;children_name&quot;)</value>
      <webElementGuid>7582f7df-2173-4e95-8864-cc5549addce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='children_name']</value>
      <webElementGuid>503110c3-36c9-4c5d-a2fd-ec1259e0b325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='membership-register']/div/div/div/form/div/div[4]/div[2]/div/input</value>
      <webElementGuid>06dc9ef2-1377-4ca2-9296-c88707f23174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>bb7723bc-10e4-4b30-a7d6-d63cc09fe041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'children_name' and @id = 'children_name' and @placeholder = 'Nama Lengkap Anak']</value>
      <webElementGuid>a5b29847-7848-45c7-85c5-7dcf34f8a78a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
