<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Referral</name>
   <tag></tag>
   <elementGuidId>b9885aa1-61d4-47a0-9e9a-1a7e6dc86a6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refferalCodeEventCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refferalCodeEventCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d11202d-9009-403c-bb3e-61602736062a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fcd7e19-c325-4975-9e88-f406dc8a2e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refferalCodeEventCode</value>
      <webElementGuid>d4254b81-f02e-4738-8585-e1709caafeb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refferalCodeEventCode</value>
      <webElementGuid>bfb9103c-e7af-4db1-a21b-05ac29cf91b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1770aa94-e277-4e77-8f53-48d037231698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kode referral teman mama di sini.</value>
      <webElementGuid>dc6af202-6778-4cf0-9ec1-ee298bd44c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>62b1317a-0147-47e2-bfae-e5a4439fbec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refferalCodeEventCode&quot;)</value>
      <webElementGuid>86e26902-ea5a-40d1-a55c-dd5a3f00137a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refferalCodeEventCode']</value>
      <webElementGuid>54d4a765-988f-4897-b12a-59e2b4ec4f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='refferalCodeEventCode_area']/input</value>
      <webElementGuid>9708797b-fee3-4666-b7dc-e5c8196c8cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/input</value>
      <webElementGuid>732d8863-0cff-4ca7-930a-cf2f7852fd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'refferalCodeEventCode' and @id = 'refferalCodeEventCode' and @placeholder = 'Masukkan kode referral teman mama di sini.']</value>
      <webElementGuid>f70ceac1-70ba-486b-a40e-598f1a67d937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
