<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Event</name>
   <tag></tag>
   <elementGuidId>69abd54a-e06c-45ec-81d2-c6dac3025930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refferalCodeEventCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refferalCodeEventCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c979bf2-fea3-435f-9646-c7756c0d035d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4c39220-19d0-4e32-8d02-42316db007b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refferalCodeEventCode</value>
      <webElementGuid>1beeef63-78cd-44af-8259-07f28947082b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refferalCodeEventCode</value>
      <webElementGuid>af4e75fa-f686-4f5e-9bcf-7eeb53ca88bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>31f139a3-7c90-4e82-9d89-fedec3397c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kode event di sini</value>
      <webElementGuid>0bcc1b51-8ca0-498d-8fcc-61941eec955b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ff047c47-72ab-4962-af43-091c376336d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refferalCodeEventCode&quot;)</value>
      <webElementGuid>887b255f-8a64-4ea0-8ddf-38c7f5a86e38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refferalCodeEventCode']</value>
      <webElementGuid>9a733d55-047e-4d2a-a63b-342a4d2d4b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='refferalCodeEventCode_area']/input</value>
      <webElementGuid>4106d08f-cb99-40bb-bf98-1ab571e1077e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/input</value>
      <webElementGuid>fd2e8073-57a1-4980-94b6-df49c1d15439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'refferalCodeEventCode' and @id = 'refferalCodeEventCode' and @placeholder = 'Masukkan kode event di sini']</value>
      <webElementGuid>31d0e348-8a8b-4216-a684-32161029e8c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
