<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text Popup Akun Mama Sudah Terdaftar</name>
   <tag></tag>
   <elementGuidId>d639f7f3-840f-47f7-8edf-7ff5ff0e4d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='modal-content-desc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-content-desc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c9c273f6-50a6-476f-9237-35f02ad559f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-content-desc</value>
      <webElementGuid>a577e646-bfdf-4311-8c6a-dca8d12fc2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akun Mama Sudah Terdaftar dan Terverifikasi.Silakan untuk login</value>
      <webElementGuid>e9adbbfa-14c1-4b41-a9d7-c2acf2559a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-content-desc&quot;)</value>
      <webElementGuid>b3905e27-6595-4391-95af-c12fe19b4b7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='modal-content-desc']</value>
      <webElementGuid>375f76cb-04b0-451e-83f7-3f2cdc2863d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-failed-register']/div/div/div[3]/p</value>
      <webElementGuid>2f88e6d5-1587-47da-8cca-f51954a6eb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terjadi Kesalahan!'])[1]/following::p[1]</value>
      <webElementGuid>de973802-de84-450a-94be-65e4608b61ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk di sini'])[1]/following::p[1]</value>
      <webElementGuid>2e18c855-c07a-46b6-991b-f6ad1bdf8dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi Kode OTP'])[1]/preceding::p[1]</value>
      <webElementGuid>e5d58085-5f8c-4a4c-8cf6-7fb6a60ded13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login di sini'])[1]/preceding::p[1]</value>
      <webElementGuid>27c23407-fcf0-47dd-8d8f-235b89ba94af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akun Mama Sudah Terdaftar dan Terverifikasi.']/parent::*</value>
      <webElementGuid>7234302f-0822-46c3-92c8-0d524bbca383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/div/div/div[3]/p</value>
      <webElementGuid>3a6f9a93-15f2-477e-8c89-b3c19943f685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'modal-content-desc' and (text() = 'Akun Mama Sudah Terdaftar dan Terverifikasi.Silakan untuk login' or . = 'Akun Mama Sudah Terdaftar dan Terverifikasi.Silakan untuk login')]</value>
      <webElementGuid>a0700fa1-1d4e-4ca1-bc7e-3c9a7d9d14a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
