<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle__switch Mama Punya Anak</name>
   <tag></tag>
   <elementGuidId>a9395273-8ebe-4bc4-b0bb-c428cab1cd30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='membership-register']/div/div/div/form/div/div[4]/div/div/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be98fada-ea06-4702-8b6c-20a9a013b9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>can-toggle__switch</value>
      <webElementGuid>b9aa078d-474e-4b04-a912-4e5784f97b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-checked</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>3e8e1f4c-6cfb-4b58-a7e2-9812866b2440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unchecked</name>
      <type>Main</type>
      <value>Tidak</value>
      <webElementGuid>52212ee3-a57e-423d-9959-eb33496c4a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;membership-register&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/form[@class=&quot;registration_form&quot;]/div[@class=&quot;register__form&quot;]/div[@class=&quot;registration__content mb-4&quot;]/div[@class=&quot;content__input&quot;]/div[@class=&quot;content__input-wrapper&quot;]/div[@class=&quot;can-toggle&quot;]/label[1]/div[@class=&quot;can-toggle__switch&quot;]</value>
      <webElementGuid>8f9c4712-0110-409c-b099-2fe1a42d5a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='membership-register']/div/div/div/form/div/div[4]/div/div/div/label/div</value>
      <webElementGuid>f2207624-3add-44f4-a091-b5e24bf65927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/label/div</value>
      <webElementGuid>9d6cc1e3-4553-407b-90ff-0e3dd67632d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
