<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle__switch Apakah Mama Sedang Hamil</name>
   <tag></tag>
   <elementGuidId>a15ee6ea-d42b-4e58-952c-eb4a07aad8e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.can-toggle__switch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='membership-register']/div/div/div/form/div/div[3]/div/div/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bebe5011-e4a0-44f6-b5e8-4283cac9900f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>can-toggle__switch</value>
      <webElementGuid>d10406b6-0566-451c-9359-c2423de6d8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-checked</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>0f06c1b7-bd7f-4ce6-a525-5d8d1d587cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unchecked</name>
      <type>Main</type>
      <value>Tidak</value>
      <webElementGuid>d4360abd-1971-4fd5-b589-b030397d9c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;membership-register&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/form[@class=&quot;registration_form&quot;]/div[@class=&quot;register__form&quot;]/div[@class=&quot;registration__content mb-4&quot;]/div[@class=&quot;content__input&quot;]/div[@class=&quot;content__input-wrapper&quot;]/div[@class=&quot;can-toggle&quot;]/label[1]/div[@class=&quot;can-toggle__switch&quot;]</value>
      <webElementGuid>5efd61a5-62af-43f1-a90d-aafd19c5f3cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='membership-register']/div/div/div/form/div/div[3]/div/div/div/label/div</value>
      <webElementGuid>38cdeb66-d162-4907-b199-ff68e6cb10d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>0d542c75-512d-45ea-a156-550cdf156dc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
