<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Toggle Switch Kode Kode referral</name>
   <tag></tag>
   <elementGuidId>0777725e-1bb8-4de4-8a14-ea589095c345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='membership-register']/div/div/div/form/div/div[5]/div/div/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a10be7bd-44d9-4fb9-b751-2644eaf62dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>can-toggle__switch</value>
      <webElementGuid>22a4fcc2-95f2-4d5a-8373-a47ccffc9f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-checked</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>a21feae9-f0bc-42d3-81a4-1338f1632cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unchecked</name>
      <type>Main</type>
      <value>Tidak</value>
      <webElementGuid>093aaad5-06b0-438b-9355-279c14d09a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;membership-register&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/form[@class=&quot;registration_form&quot;]/div[@class=&quot;register__form&quot;]/div[@class=&quot;registration__content mb-4&quot;]/div[@class=&quot;content__input&quot;]/div[@class=&quot;content__input-wrapper&quot;]/div[@class=&quot;can-toggle&quot;]/label[1]/div[@class=&quot;can-toggle__switch&quot;]</value>
      <webElementGuid>1c5e50e1-13f7-4e26-aed8-6fed146718c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='membership-register']/div/div/div/form/div/div[5]/div/div/div/label/div</value>
      <webElementGuid>4c5f3f6f-0e1d-41de-b314-4ca4485415ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/label/div</value>
      <webElementGuid>36f0f0d3-3b74-4e22-b3de-2211d71957ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
