<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Banner</name>
   <tag></tag>
   <elementGuidId>c3c030d9-49d9-492b-9ee0-c0ae1d10c972</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>picture > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='slick-slide00']/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>51b3221b-59aa-42a3-ab7b-5da8bb155d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/membership-homepage/image-thumb__332197__default/nutriclub-banner-uvp-desktop.webp</value>
      <webElementGuid>827a79be-30e0-4f31-ace2-939dcc9cd4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3524dca5-659f-4249-8e0c-9a7b5033ff1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>465</value>
      <webElementGuid>2fd1f2ef-68ea-46d9-8ffe-06b61a047488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide00&quot;)/a[1]/div[1]/picture[1]/img[1]</value>
      <webElementGuid>1256521e-9334-4fed-b93d-e5abd3e16cb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='slick-slide00']/a/div/picture/img</value>
      <webElementGuid>fce31726-5e9e-440c-98c5-1fd336ab2ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>54213743-733e-4778-a76f-01e5ca3c59dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/membership-homepage/image-thumb__332197__default/nutriclub-banner-uvp-desktop.webp']</value>
      <webElementGuid>f338ffb6-3421-4912-a64b-0356d9caff2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
