<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Undang Banyak Teman</name>
   <tag></tag>
   <elementGuidId>2016a8c4-fb23-4cf3-9cb3-8b349fbc78cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.d-block.w-90.mx-auto.mb-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='encourage-register']/div/div/div/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8813d4c8-59a4-4370-af32-4ac0b3125fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>354</value>
      <webElementGuid>7b82887e-dca9-41eb-ad97-a9c133d37441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>237</value>
      <webElementGuid>4f14cf3c-e603-4505-b3dd-af1eeb295a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_default_upload_bucket/image-thumb__335327__default/encourage-register-mobile-0.webp</value>
      <webElementGuid>7dc9022b-6362-46f7-ad7c-47b8b4075013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Gambar Ayo Undang Banyak Teman</value>
      <webElementGuid>1b6bfc45-b90c-45fa-bfe4-3e84d8dd4cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Gambar Ayo Undang Banyak Teman</value>
      <webElementGuid>609bb2e2-d793-4b29-91e7-d6fc9082a044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>ffea9fab-1e55-4720-8c79-ef7b681f07a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-block w-90 mx-auto mb-4</value>
      <webElementGuid>0b869d79-658a-48df-a29e-21c1934e1057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;encourage-register&quot;)/div[@class=&quot;container-fluid bg-white py-4&quot;]/div[@class=&quot;row d-flex justify-content-center&quot;]/div[@class=&quot;col col-md-10 bg-blue-100 py-4 px-3 p-md-5 rounded-3 rounded-sm-0 d-md-flex justify-content-md-center gap-2&quot;]/div[@class=&quot;encourage-register-image-wrapper w-40 w-sm-100i mx-auto&quot;]/picture[@class=&quot;mb-4&quot;]/img[@class=&quot;d-block w-90 mx-auto mb-4&quot;]</value>
      <webElementGuid>0af0ab95-1413-4329-8d24-3f7e238adc6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='encourage-register']/div/div/div/div/picture/img</value>
      <webElementGuid>ac9efc12-7e1a-498a-891b-62b01380f3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Gambar Ayo Undang Banyak Teman']</value>
      <webElementGuid>4a68d7a0-4487-4a3c-b231-e01e90322c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/section/div/div/div/div/picture/img</value>
      <webElementGuid>a839c904-0b14-4e9f-aeba-277c78ca8723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_default_upload_bucket/image-thumb__335327__default/encourage-register-mobile-0.webp' and @alt = 'Gambar Ayo Undang Banyak Teman' and @title = 'Gambar Ayo Undang Banyak Teman']</value>
      <webElementGuid>a18113e6-5f4b-41f3-8096-4fbe83bf7b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
