<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Banner Produk Page</name>
   <tag></tag>
   <elementGuidId>911f8ef4-4b35-4789-a0ad-252bfc667acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.w-100.d-none.d-sm-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://d6h6jrckowxli.cloudfront.net/product/banner/image-thumb__379288__card-product-banner-thumbnail/banner-product-parent-mobile.webp')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ef389e5-4cae-42a3-801d-893dd4eed12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>8333</value>
      <webElementGuid>ce604563-d5b3-4268-a00e-00be12ce342c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1517</value>
      <webElementGuid>b49d0cb1-cc57-45f4-9a1d-8c73954535b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid w-100 d-none d-sm-block</value>
      <webElementGuid>c332ba89-fe66-4581-b902-8901dab84514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/product/banner/image-thumb__379288__card-product-banner-thumbnail/banner-product-parent-mobile.webp</value>
      <webElementGuid>d4cf05ba-94d0-4227-9d77-830d1d7b98e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/product/banner/image-thumb__379288__card-product-banner-thumbnail/banner-product-parent-mobile.webp 1x, https://d6h6jrckowxli.cloudfront.net/product/banner/image-thumb__379288__card-product-banner-thumbnail/banner-product-parent-mobile@2x.webp 2x</value>
      <webElementGuid>f10d098e-f095-45ba-88b2-aa04c6800a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;main-parent-product nutriclub-content-product&quot;]/div[@class=&quot;pimcore_area_card-product-banner pimcore_area_content&quot;]/div[@class=&quot;content-porduct_header&quot;]/div[@class=&quot;content-porduct_header_bg&quot;]/div[@class=&quot;bg-header-detail&quot;]/img[@class=&quot;img-fluid w-100 d-none d-sm-block&quot;]</value>
      <webElementGuid>9eed20be-d37a-496d-b7f3-c55361222e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d6h6jrckowxli.cloudfront.net/product/banner/image-thumb__379288__card-product-banner-thumbnail/banner-product-parent-mobile.webp')]</value>
      <webElementGuid>9aa9dc92-5d90-4430-8d6a-ee9dbf9ca723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>3b13aa5b-e4e3-47cb-aa8f-e1efedd8ab9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d6h6jrckowxli.cloudfront.net/product/banner/image-thumb__379288__card-product-banner-thumbnail/banner-product-parent-mobile.webp']</value>
      <webElementGuid>2d24ce50-0133-4c9a-841e-de1efd6543eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
