<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Nutrilon Royal 4</name>
   <tag></tag>
   <elementGuidId>8283dbb2-be53-462c-aee8-a06c7e91217a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='tahapan-product-landing']/div/div/div[2]/div[2]/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>2098d182-0700-466d-bafc-c3fa991aa3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nutrilon Royal 4</value>
      <webElementGuid>79d34b3b-8993-4676-a9a9-d5a5aa7a80f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tahapan-product-landing&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;row tahapan-product-landing-card-wrapper&quot;]/div[@class=&quot;col-md-12 tahapan-card-list-item&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;content-title&quot;]/h3[1]</value>
      <webElementGuid>fb80f8b1-b99d-48bd-b2e2-ea062e31f511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='tahapan-product-landing']/div/div/div[2]/div[2]/div/div/h3</value>
      <webElementGuid>77bd9652-9d27-4de4-98f7-09aa832e79c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nutrilon Royal 3'])[3]/following::h3[1]</value>
      <webElementGuid>235e3044-2255-40ad-8f8e-8e866dfa7c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahapan Susu Nutrilon Royal'])[1]/following::h3[2]</value>
      <webElementGuid>ea37e807-1a45-4808-bc51-3f344b029b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Varian Nutrilon Royal'])[1]/preceding::h3[1]</value>
      <webElementGuid>ff7a2ae0-d94e-4ccb-854b-170850549cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nutrilon Royal Rasa Vanila'])[1]/preceding::h3[1]</value>
      <webElementGuid>a5c1828f-ab8b-49a4-a2f5-a964b122ac07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/div/div/h3</value>
      <webElementGuid>0319fa01-3a67-406c-8df1-f13c5d4f06ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Nutrilon Royal 4' or . = 'Nutrilon Royal 4')]</value>
      <webElementGuid>a18ce978-8f2a-4bb9-910f-a95e2a3dbd92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
