<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_NR4</name>
   <tag></tag>
   <elementGuidId>9a8dfaa2-db97-43e5-95a6-fa3168391661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-product-parent-page.nutrilon-4 > a > div.image-area > img.img-fluid.image-card-product-parent-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332653__default/nutrilon-royal-4_1%402x%20%281%29.webp')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8a9ef0c0-3f76-4ec3-9c1b-91d309ad194c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>245</value>
      <webElementGuid>13ee3042-3497-4df6-b751-32b77d1239ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>185</value>
      <webElementGuid>e6bc6e3b-681b-4dbb-863a-f2ba22a3e0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid image-card-product-parent-page</value>
      <webElementGuid>b4bbda7f-c271-4d0d-baa6-6b028a077b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332653__default/nutrilon-royal-4_1%402x%20%281%29.webp</value>
      <webElementGuid>b8d79838-5509-4b12-b756-9a410148ba28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332653__default/nutrilon-royal-4_1%402x%20%281%29.webp 1x, https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332653__default/nutrilon-royal-4_1%402x%20%281%29@2x.webp 2x</value>
      <webElementGuid>747bca36-d1b6-4854-bb8b-17cb32a530f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;main-parent-product nutriclub-content-product&quot;]/div[@class=&quot;pimcore_area_card-product-list-enhancement pimcore_area_content&quot;]/div[@class=&quot;content-detail_product-list&quot;]/div[@class=&quot;row product-list-wrapper&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;card-product-parent-page nutrilon-4&quot;]/a[1]/div[@class=&quot;image-area&quot;]/img[@class=&quot;img-fluid image-card-product-parent-page&quot;]</value>
      <webElementGuid>87631e6e-558e-4d69-9eb6-86b760e425f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332653__default/nutrilon-royal-4_1%402x%20%281%29.webp')]</value>
      <webElementGuid>fe874ca4-44be-4c4d-a200-f59cc57426f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div/img</value>
      <webElementGuid>0708ffb0-570e-45e4-ac91-61d940f529e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332653__default/nutrilon-royal-4_1%402x%20%281%29.webp']</value>
      <webElementGuid>388f8bd6-a9e2-4721-81ef-7a5ae7aa4161</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
