<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_NR3</name>
   <tag></tag>
   <elementGuidId>45df7a2a-81ec-4119-a7b1-2b38f94582a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.image-card-product-parent-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332652__default/nutrilon-royal-3_1%402x%20%281%29.webp')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>16a5439e-82aa-47bd-87c7-5f4e8fa7cc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>245</value>
      <webElementGuid>ca55919f-13b7-4ef7-a92f-5969eef19ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>185</value>
      <webElementGuid>93ac53e6-0a3d-44d0-8260-355a9027b4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid image-card-product-parent-page</value>
      <webElementGuid>5077e7c8-0e2d-4f36-bab0-8de160549d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332652__default/nutrilon-royal-3_1%402x%20%281%29.webp</value>
      <webElementGuid>46d18f12-5b94-47ea-9203-f9f1ce0b8a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332652__default/nutrilon-royal-3_1%402x%20%281%29.webp 1x, https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332652__default/nutrilon-royal-3_1%402x%20%281%29@2x.webp 2x</value>
      <webElementGuid>78ef5b10-397c-47bc-9750-ab8bfec81a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;main-parent-product nutriclub-content-product&quot;]/div[@class=&quot;pimcore_area_card-product-list-enhancement pimcore_area_content&quot;]/div[@class=&quot;content-detail_product-list&quot;]/div[@class=&quot;row product-list-wrapper&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;card-product-parent-page nutrilon-3&quot;]/a[1]/div[@class=&quot;image-area&quot;]/img[@class=&quot;img-fluid image-card-product-parent-page&quot;]</value>
      <webElementGuid>10fcf5d4-1ab2-45a4-ab22-9b40663e8b59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332652__default/nutrilon-royal-3_1%402x%20%281%29.webp')]</value>
      <webElementGuid>dc432a4c-0f3a-4843-8e85-2bf8fa42d526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/div/img</value>
      <webElementGuid>e555fb13-8880-4350-b422-2333b7d497e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__332652__default/nutrilon-royal-3_1%402x%20%281%29.webp']</value>
      <webElementGuid>359a39b1-d36c-4d09-b0b9-afa3cb684fdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
