<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_produk lainnya_img-fluid image-card</name>
   <tag></tag>
   <elementGuidId>46696921-42a9-4845-97a3-47907cfece85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-product-parent-page.neocate > a > div.image-area > img.img-fluid.image-card-product-parent-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='other-product-landing']/div/div[2]/div[2]/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>16c5a342-607b-4ad1-a480-1b3c3e64c01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>320</value>
      <webElementGuid>e67113a4-d55e-4364-9c70-f64e75d99641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>187</value>
      <webElementGuid>1ae09a43-9dfe-4e3f-b75c-fa49c3decec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid image-card-product-parent-page</value>
      <webElementGuid>54cc9542-0e14-40a5-82d4-9af230f47cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__388220__default/Neocate%20Junior_AUG%202022%20%281%29.webp</value>
      <webElementGuid>092ab102-f735-4717-abd4-df6c691a4310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__388220__default/Neocate%20Junior_AUG%202022%20%281%29.webp 1x, https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__388220__default/Neocate%20Junior_AUG%202022%20%281%29@2x.webp 2x</value>
      <webElementGuid>7c2485ac-168f-4707-af1f-e48c65f0c2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;other-product-landing&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row product-list-wrapper&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;card-product-parent-page neocate&quot;]/a[1]/div[@class=&quot;image-area&quot;]/img[@class=&quot;img-fluid image-card-product-parent-page&quot;]</value>
      <webElementGuid>80e944b7-7618-4a7b-8555-d8d39cbdb37e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='other-product-landing']/div/div[2]/div[2]/div/a/div/img</value>
      <webElementGuid>7a1c61e9-617f-4c8b-98a1-d6bbfcfe2e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__388220__default/Neocate%20Junior_AUG%202022%20%281%29.webp')]</value>
      <webElementGuid>52e6f41b-e557-4673-98e1-04bfecbe242a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a/div/img</value>
      <webElementGuid>c2fd0ac4-9eca-4375-8390-e32432753709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__388220__default/Neocate%20Junior_AUG%202022%20%281%29.webp']</value>
      <webElementGuid>f885956e-6fa0-4358-89fa-8acb5155f32f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
