<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Susu Nutrilon Lainnya</name>
   <tag></tag>
   <elementGuidId>cf63a124-5871-4e0a-84b1-7deae9483f24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-product-parent-page.nutrinidrink > a > div.image-area > img.img-fluid.image-card-product-parent-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='other-product-landing']/div/div[2]/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>02398c17-b9eb-4dfa-b854-0212060dc6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>320</value>
      <webElementGuid>af10f64c-8fdb-43bd-a765-8411b9be35a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>187</value>
      <webElementGuid>1dd6246c-ae1b-4d38-8063-8ac43b5d5efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid image-card-product-parent-page</value>
      <webElementGuid>f1ef9739-46ec-4ef6-bb29-7f1aee7e0e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__434898__default/PRODUK%20NUTRINIDRINK_1.webp</value>
      <webElementGuid>ea879f17-cb77-4d2b-b97e-344154a72e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__434898__default/PRODUK%20NUTRINIDRINK_1.webp 1x, https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__434898__default/PRODUK%20NUTRINIDRINK_1@2x.webp 2x</value>
      <webElementGuid>3939c18b-15d4-414c-be55-f7e9c8e056be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;other-product-landing&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row product-list-wrapper&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;card-product-parent-page nutrinidrink&quot;]/a[1]/div[@class=&quot;image-area&quot;]/img[@class=&quot;img-fluid image-card-product-parent-page&quot;]</value>
      <webElementGuid>a399f197-cfc6-4338-8755-9a9c90c2a3ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='other-product-landing']/div/div[2]/div/div/a/div/img</value>
      <webElementGuid>65761c19-3eef-4721-b140-7370afd38b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__434898__default/PRODUK%20NUTRINIDRINK_1.webp')]</value>
      <webElementGuid>adf4567e-06eb-4e75-ac39-584c5d5aa21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/img</value>
      <webElementGuid>bf826da2-4db6-4c80-bbc6-300e24360d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d6h6jrckowxli.cloudfront.net/_default_upload_bucket/image-thumb__434898__default/PRODUK%20NUTRINIDRINK_1.webp']</value>
      <webElementGuid>396cf772-a26e-48fa-b1c9-b8f6a86591f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
