<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Image Popup Modal Unregistered Member</name>
   <tag></tag>
   <elementGuidId>d88d4d0c-500c-4281-9466-dc0c3b226af0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-otp-member-hp-not-found']/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bc8c183a-11b1-4586-b80f-30aea0a92cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>/assets/images/icons/icon-family.webp</value>
      <webElementGuid>29c738ae-4d16-4d59-a607-1e5e7049a234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> lazyloaded</value>
      <webElementGuid>70a1c6ff-9b40-47d0-b7ee-a2f0512d1b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>family icons</value>
      <webElementGuid>889c5f45-0695-4f28-b948-eeed34dca142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>163</value>
      <webElementGuid>25148a3a-9174-4c45-ad28-1312e088e773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>188</value>
      <webElementGuid>a3f6b55f-c7f7-40a0-9309-bec7dd00c198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icons/icon-family.webp</value>
      <webElementGuid>7bc262ea-ad8c-4e16-84a9-dd729438f437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-otp-member-hp-not-found&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content p-4&quot;]/div[@class=&quot;modal__error-figure&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>837ee3ca-65d2-4f6f-95f6-476d845e2a86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-otp-member-hp-not-found']/div/div/div[2]/img</value>
      <webElementGuid>7c66da88-f05f-4d75-8660-383cc8018040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='family icons']</value>
      <webElementGuid>d88254c9-efac-4628-87a2-c215e81e5b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>84504218-5793-440b-8761-bb18791baacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'family icons' and @src = '/assets/images/icons/icon-family.webp']</value>
      <webElementGuid>da0af12c-a71a-46b6-b06b-f69448b14d4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
